name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install toolchains
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            mingw-w64

      - name: Linux build
        run: |
          make clean
          make

      - name: Linux upload
        uses: actions/upload-artifact@v4
        with:
          name: acftool-linux
          path: acftool

      - name: Windows build
        run: |
          make clean
          make CC=x86_64-w64-mingw32-gcc \
               TARGET=acftool.exe \
               LDFLAGS="-static"

      - name: Windows upload
        uses: actions/upload-artifact@v4
        with:
          name: acftool-windows
          path: acftool.exe
